AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Swift Application

Globals:
  Function:
    Timeout: 10
    CodeUri: .
    Handler: swift.bootstrap
    Runtime: provided.al2
    MemorySize: 512

Resources:
  PiUrlSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: pi-url
      Description: Secret to store the Pi URL
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SwiftEverywhere
      AttributeDefinitions:
        - AttributeName: partition
          AttributeType: S
        - AttributeName: uploadDate
          AttributeType: S
      KeySchema:
        - AttributeName: partition
          KeyType: HASH
        - AttributeName: uploadDate
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  SwiftEverywhereAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'content-type'"
        AllowOrigin: "'*'"
        AllowCredentials: "'*'"
  SELambda:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Architectures:
        - arm64
      Events:
        analogReadingsGet:
          Type: Api
          Properties:
            Path: /analogReadings/{id}
            Method: get
            RestApiId: !Ref SwiftEverywhereAPI
        analogReadingsSearch:
          Type: Api
          Properties:
            Path: /analogReadings
            Method: get
            RestApiId: !Ref SwiftEverywhereAPI
        analogReadingPost:
          Type: Api
          Properties:
            Path: /analogReadings/{id}
            Method: post
            RestApiId: !Ref SwiftEverywhereAPI
        deviceTokenPost:
          Type: Api
          Properties:
            Path: /deviceToken
            Method: post
            RestApiId: !Ref SwiftEverywhereAPI
        digitalValuesGet:
          Type: Api
          Properties:
            Path: /digitalValues/{id}
            Method: get
            RestApiId: !Ref SwiftEverywhereAPI
        digitalValuesPost:
          Type: Api
          Properties:
            Path: /digitalValues
            Method: post
            RestApiId: !Ref SwiftEverywhereAPI
        HostGet:
          Type: Api
          Properties:
            Path: /host
            Method: get
            RestApiId: !Ref SwiftEverywhereAPI
        HostPost:
          Type: Api
          Properties:
            Path: /host
            Method: post
            RestApiId: !Ref SwiftEverywhereAPI
        pushNotificationPost:
          Type: Api
          Properties:
            Path: /pushNotification
            Method: post
            RestApiId: !Ref SwiftEverywhereAPI
      Policies:
        - AmazonDynamoDBFullAccess
        - Statement:
            Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:pi-url*"
        - Statement:  # Grant permissions to publish to all APNS_SANDBOX platform applications
            Effect: Allow
            Action:
              - sns:CreatePlatformEndpoint
              - sns:Publish
            Resource: !Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:app/APNS_SANDBOX/*"
      Environment:
        Variables:
          PI_URL_SECRET_NAME: "pi-url"

Outputs:
  ApiEndpoint:
    Description: "API endpoint URL"
    Value: !Sub "https://${SwiftEverywhereAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod"
