AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Swift Application

Globals:
  Function:
    Timeout: 10
    CodeUri: . 
    Handler: swift.bootstrap
    Runtime: provided.al2
    MemorySize: 512

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: SwiftEverywhere
      AttributeDefinitions:
        - AttributeName: partition
          AttributeType: S
        - AttributeName: uploadDate
          AttributeType: S
      KeySchema:
        - AttributeName: partition
          KeyType: HASH
        - AttributeName: uploadDate
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  SwiftEverywhereAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'content-type'"
        AllowOrigin: "'*'"
        AllowCredentials: "'*'"
  SwiftEverywhereLambda:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      Architectures:
      - arm64
      Events:
        ledGet:
          Type: Api
          Properties:
            Path: /led
            Method: get
            RestApiId: !Ref SwiftEverywhereAPI
        ledPost:
          Type: Api
          Properties:
            Path: /led
            Method: post
            RestApiId: !Ref SwiftEverywhereAPI
      Policies:
      - AmazonDynamoDBFullAccess
Outputs:
  ApiEndpoint:
    Description: "API endpoint URL"
    Value: !Sub "https://${SwiftEverywhereAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod"
